# Generated by Django 6.0.6 on 2026-07-13 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=200, verbose_name='city')),
                ('Title', models.CharField(max_length=200, verbose_name='title')),
                ('Address', models.TextField(unique=True, verbose_name='address')),
                ('Capacity', models.IntegerField(verbose_name='capacity')),
                ('Price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price_per_night')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
