# Generated by Django 6.0.6 on 2026-07-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('villa_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=200, verbose_name='city')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('address', models.TextField(unique=True, verbose_name='address')),
                ('capacity', models.IntegerField(verbose_name='capacity')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price_per_night')),
                ('amenities', models.TextField(blank=True, null=True)),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
