# Generated by Django 6.0.6 on 2026-07-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Villas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='amenities',
            field=models.JSONField(default=dict),
        ),
    ]
