# Generated by Django 6.0.6 on 2026-07-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Villas', '0002_alter_villa_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='price_per_night',
            field=models.IntegerField(verbose_name='price_per_night'),
        ),
    ]
