# Generated by Django 6.0.6 on 2026-07-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Villas', '0002_alter_villa_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('A', 'available'), ('R', 'reserved'), ('N', 'not added by host')], default='A', max_length=1)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Villas.villa')),
            ],
            options={
                'unique_together': {('villa', 'date')},
            },
        ),
    ]
