# Generated by Django 6.0.6 on 2026-07-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='jalali_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
